/*
    This file is part of MiraMon Map Browser.
    MiraMon Map Browser is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    MiraMon Map Browser is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    See the GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General
    Public License along with MiraMon Map Browser.
    If not, see https://www.gnu.org/licenses/licenses.html#AGPL.

    MiraMon Map Browser can be updated from
    https://github.com/grumets/MiraMonMapBrowser.

    Copyright 2001, 2022 Xavier Pons

    Aquest codi JavaScript ha estat idea de Joan Masó Pau (joan maso at uab cat)
    amb l'ajut de Alba Brobia (a brobia at creaf uab cat)
    dins del grup del MiraMon. MiraMon és un projecte del
    CREAF que elabora programari de Sistema d'Informació Geogràfica
    i de Teledetecció per a la visualització, consulta, edició i anàlisi
    de mapes ràsters i vectorials. Aquest progamari programari inclou
    aplicacions d'escriptori i també servidors i clients per Internet.
    No tots aquests productes són gratuïts o de codi obert.

    En particular, el Navegador de Mapes del MiraMon (client per Internet)
    es distribueix sota els termes de la llicència GNU Affero General Public
    License, mireu https://www.gnu.org/licenses/licenses.html#AGPL.

    El Navegador de Mapes del MiraMon es pot actualitzar des de
    https://github.com/grumets/MiraMonMapBrowser.
*/

"use strict"

var MessageLang={
	MissingMessage: {"cat":"Missatge no trobat", "spa":"Mensage no encontrado", "eng":"Missing message", "fre":"Message non trouvé"},
	ModifyName: {"cat":"Modifica el nom", "spa":"Modifica el nombre", "eng":"Modify the name", "fre":"Modifier le nom"},
	AddLayer: {"cat":"Afegir capa", "spa":"A&ntilde;adir capa", "eng":"Add layer", "fre":"Ajouter couche"},
	Georeference: {"cat":"Georeferència","spa":"Georeferencia", "eng":"Georeference", "fre":"Géoréférence"},
	Coordinates: {"cat":"Coordenades","spa":"Coordenadas", "eng":"Coordinates", "fre":"Coordonnées"},
	CentralPoint: {"cat":"Punt central","spa":"Punto central", "eng":"Central point", "fre":"Point central"},
	CurrentReferenceSystem: {"cat":"Sistema de referència actual", "spa":"Sistema de referencia actual", "eng":"Current reference system", "fre":"Système de référence actuel"}, 
	AvailableBoundary: {"cat":"Àmbit disponible", "spa":"Ámbito disponible", "eng":"Available boundary", "fre":"Champ disponible"},
	CellSize: {"cat": "Costat de cel·la", "spa": "Lado de celda", "eng": "Cell size", "fre": "Taille de la cellule"},
	CellArea: {"cat": "Àrea de la cel·la", "spa": "Área de celda", "eng": "Cell area", "fre": "Zone de la cellule"},
	Metadata: {"cat":"Metadades", "spa":"Metadatos", "eng":"Metadata", "fre":"Métadonnées"},
	Quality: {"cat":"Qualitat", "spa":"Calidad", "eng":"Quality", "fre":"Qualité"},
	Lineage: {"cat":"Llinatge", "spa":"Linaje", "eng":"Lineage", "fre":"Lignage"},
	Feedback: {"cat":"Valoracions", "spa":"Valoraciones", "eng":"Feedback", "fre":"rétroaction"},
	PieChart: {"cat":"Gràfic circular", "spa":"Gráfico circular", "eng":"Pie chart", "fre":"Diagramme à secteurs"},
	Histogram: {"cat":"Histograma", "spa":"Histograma", "eng":"Histogram", "fre":"Histogramme"},
	Selection:{"cat":"Selecció", "spa":"Selección", "eng":"Selection", "fre":"Sélection"},
	Open: {"cat":"Obrir", "spa":"Abrir", "eng":"Open","fre":"Ouvrir"},
	Save: {"cat":"Desar","spa":"Guardar","eng":"Save","fre":"Sauvegarder"},
	close: {"cat":"tancar", "spa":"cerrar", "eng":"close", "fre":"quitter"},
	Close: {"cat":"Tancar", "spa":"Cerrar", "eng":"Close", "fre":"Quitter"},
	Show: {"cat":"Mostrar", "spa":"Mostrar", "eng":"Show", "fre":"Afficher"},
  UnderDevelopment: {"cat":"En desenvolupament.", "spa":"En desarrollo.", "eng":"Under development.", "fre":"En développement."},
  layer: {"cat":"capa", "spa":"capa", "eng":"layer", "fre":"couche"},
  Layer: {"cat":"Capa", "spa":"Capa", "eng":"Layer", "fre":"Couche"},
  LayerId: {"cat":"Identificador de la capa", "spa":"Identificador de la capa", "eng":"Layer identifier", "fre":"Identificateur de couche"},
  Layers: {"cat":"Capes","spa":"Capas","eng":"Layers","fre":"Couches"},
	TheLayer: {"cat":"La capa", "spa":"La capa", "eng":"The layer", "fre":"La couche"},
	ofTheLayer: {"cat": "de la capa", "spa": "de la capa", "eng": "of the layer", "fra": "de la couche"},
  Add: {"cat":"Afegir", "spa":"Añadir", "eng":"Add", "fre":"Ajouter"},
  Expression: {"cat":"Fórmula", "spa":"Fórmula:", "eng":"Expression", "fre":"Formule"},
  Value: {"cat":"Valor", "spa":"Valor", "eng":"Value", "fre":"Valeur"},
	TheValue:{"cat":"El valor", "spa":"El valor", "eng":"The value", "fre":"La valeur"},
  Operator: {"cat":"Operador", "spa":"Operador", "eng":"Operator", "fre":"Opérateur"},
  Date: {"cat":"Data", "spa":"Fecha", "eng":"Date", "fre":"Date"},
  Field: {"cat":"Camp", "spa":"Camp", "eng":"Field", "fre":"Champ"},
	ofTheField:{"cat":"del camp", "spa": "del campo", "eng": "of the field", "fre": "du champ"},
  Title: {"cat":"T&iacute;tol", "spa":"T&iacute;tulo", "eng":"Title", "fre":"Titre"},
  Condition: {"cat":"Condició", "spa":"Condición", "eng":"Condition", "fre":"Condition"},
	OK: {"cat":"Acceptar", "spa":"Aceptar", "eng":" OK ", "fre":"Accepter"},
	Cancel: {"cat":"Cancel·lar", "spa":"Cancelar", "eng":"Cancel", "fre":"Annuler"},
	Apply: {"cat":"Aplicar", "spa":"Aplicar", "eng":"Apply", "fre":"Appliquer"},
  Presentation: {"cat":"Presentació", "spa":"Presentación","eng":"Presentation", "fre":"Présentation"},
  Graphical: {"cat":"Gràfica", "spa":"Gráfica", "eng":"Graphical", "fre":"Graphique"},
  Textual: {"cat":"Textual", "spa":"Textual", "eng":"Textual", "fre":"Textuelle"},
  Unsorted: {"cat":"Cap", "spa":"Ninguno", "eng":"Unsorted", "fre":"Non trié"},
  ColorPalette: {"cat":"Paleta de colors", "spa":"Paleta de colores", "eng":"Color palette", "fre":"Palette de couleurs"},
  Colors: {"cat":"Colors","spa":"Colores", "eng":"Colors", "fre":"Couleurs"},
  Current: {"cat": "Actual", "spa": "Actual", "eng": "Current", "fre": "Actuel"},
  Previous: {"cat": "Prèvia", "spa": "Previa", "eng": "Previous", "fre": "Précédente"},
	View: {"cat":"Vista","spa":"Vista", "eng":"View", "fre":"Vue"},
	Width: {"cat":"Ample", "spa":"Ancho", "eng":"Width", "fre":"Largeur"},
	Height: {"cat":"Alt", "spa":"Alto", "eng":"Height", "fre":"Hauteur"},
  LayerName:{"cat":"Nom de la capa", "spa":"Nombre de la capa", "eng":"Name of the layer", "fre":"Nom de la couche"},
  ModalClass: {"cat": "Classe modal", "spa": "Clase modal", "eng": "Modal class", "fre": "Classe modale"},
  PercentageMode: {"cat": "Percentatge de la moda", "spa": "Porcentaje de la moda", "eng": "Percentage of the mode", "fre": "Pourcentage de mode"},
  Sum: {"cat": "Suma", "spa": "Suma", "eng": "Sum", "fre": "Somme"},
  SumArea: {"cat": "Suma àrea", "spa": "Suma área", "eng": "Sum area", "fre": "Somme area"},
  Mean: {"cat": "Mitjana", "spa": "Media", "eng": "Mean", "fre": "Moyenne"},
  Variance: {"cat": "Variança", "spa": "Varianza", "eng": "Variance", "fre": "Variance"},
  StandardDeviation: {"cat": "Desviació estàndard", "spa": "Desviació estándar", "eng": "Standard deviation", "fre": "Écart-type"},
  Minimum: {"cat":"Mínim", "spa":"Mínimo", "eng":"Minimum", "fre":"Minimum"},
	Maximum: {"cat":"Màxim", "spa":"Máximo", "eng":"Maximum", "fre":"Maximum"},
  Range: {"cat": "Rang", "spa": "Rango", "eng": "Range", "fre": "Gamme"},
  SortingOrder: {"cat":"Ordre", "spa":"Orden","eng":"Sorting order", "fre":"Ordre de tri"},
  Others: {"cat":"Altres", "spa":"Otros", "eng":"Others", "fre":"Autres"},
	Link: {"cat":"Enllaç", "spa":"Enlace", "eng":"Link", "fre":"Relier"},
	Point: {"cat":"Punt", "spa":"Punto", "eng":"Point", "fre":"Point"},
	Query: {"cat":"Consulta", "spa":"Consulta", "eng":"Query","fre":"Recherche"},
	Select: {"cat":"Seleccionar", "spa":"Seleccionar", "eng":"Select", "fre":"Sélectionner"},
  pleaseWait: {"cat":"espereu", "spa":"espere", "eng":"please wait","fre":"attendez"},
	PleaseWait: {"cat":"Espereu si us plau", "spa":"Espere por favor", "eng":"Please, wait", "fre":"Attendez, s'il-vous-plaît"},
	DateTime: {"cat":"Data i hora","spa":"Fecha y hora", "eng": "Date and time","fre":"Date et l'heure"},
	Next: {"cat":"Següent", "spa":"Siguiente", "eng":"Next", "fre":"Suivant"},
	Format: {"cat": "Format", "spa": "Formato", "eng": "Format", "fre": "Format"},
	Download: {"cat":"Descarregar","spa":"Descargar","eng":"Download","fre":"Télécharger"},
	of: {"cat":"de","spa":"de", "eng":"of","fre":"de"},
	Time: {"cat": "Hora", "spa": "Hora", "eng": "Time", "fre": "L'heure"},
	Option: {"cat": "Opció", "spa": "Opición", "eng": "Option", "fre": "Option"},
	Status: {"cat":"Estat", "spa":"Estado", "eng":"Status", "fre":"Statut"},
	Coordinates: {"cat":"Coordenades", "spa":"Coordenadas", "eng":"Coordinates", "fre":"Coordonnées"},
	tabSeparatedText: {"cat": "text separat per tabulacions", "spa": "texto separado por tabulaciones", "eng": "tab-separated text", "fre": "texte séparé par des tabulations"},
	Style: {"cat": "Estil", "spa": "Estilo", "eng": "Style", "fre": "Style"},
	Count: {"cat": "Recompte", "spa": "Cuenta", "eng": "Count", "fre": "Compter"},
	Area: {"cat": "Àrea", "spa": "Área", "eng": "Area", "fre": "Zone"},
	NoData: {"cat": "Sense dades", "spa": "Sin datos", "eng": "No data", "fre": "Pas de données"},
	Class: {"cat": "Classe", "spa": "Clase", "eng": "Class", "fre": "Classe"},
	All: {"cat": "Totes", "spa": "Todas", "eng": "All", "fre": "Toutes"},
	Dynamic: {"cat":"Dinàmic", "spa":"Dinámico", "eng":"Dynamic", "fre":"Dynamique"},
	Disabled: {"cat":"Desactivat)", "spa":"Desactivado", "eng":"Disabled", "fre":"Désactivé"},
	layerOrStyleNotVisible: {"cat":"capa o estil no visible", "spa":"capa o estil no visible", "eng":"layer or style not visible", "fre":"couche or style non visible"},
	Statistics: {"cat":"Estadístics", "spa":"Estadísticos", "eng":"Statistics", "fre":"Statistique"},
	Statistic: {"cat": "Estadístic", "spa": "Estadístico", "eng": "Statistic", "fre": "Statistique"},
	ContingencyTable: {"cat":"Taula de contingència", "spa":"Tabla de contingencia", "eng":"Contingency table", "fre":"Tableau de contingence"},
  Columns: {"cat": "Columnes", "spa": "Columnas", "eng": "Columns", "fre": "Colonnes"},
	columns: {"cat": "columnes", "spa": "columnas", "eng": "columns", "fre": "colonnes"},
  Rows: {"cat": "Files", "spa": "Filas", "eng": "Rows", "fre": "Lignes"},
	rows: {"cat": "files", "spa": "filas", "eng": "rows", "fre": "lignes"},
	Shown: {"cat": "Mostrades", "spa": "Mostradas", "eng": "Shown", "fre": "Montré"},
	Name: {"cat": "Nom", "spa": "Nombre", "eng": "Name", "fre": "Nom"},
	Band: {"cat": "Banda", "spa": "Banda", "eng": "Band", "fre": "Bande"},
	Measure: {"cat": "Mesura", "spa": "Medida", "eng": "Measure", "fre": "Mesure"},
	copy: {"cat":"copiar", "spa":"copiar", "eng":"copy","fre":"copier"},
	KappaCoef:{"cat": "Index Kappa", "spa": "Indice Kappa", "eng": "Kappa coefficient", "fre": "Coefficient kappa"},
	none: {"cat":"cap", "spa":"ninguno", "eng":"none", "fre":"aucun"},
	and: {"cat": "i", "spa": "y", "eng": "and", "fre": "et"},
	or: {"cat":"o", "spa":"o", "eng":"or", "fre":"ou"},
	Working: {"cat":"Processant", "spa":"Procesando", "eng":"Working", "fre":"En traitement"},
	cntxmenu: {
		ShareLayer: {"cat":"Compartir capa", "spa":"Compartir capa", "eng":"Share layer", "fre":"Partager couche"},
		RemoveLayer: {"cat":"Esborrar capa", "spa":"Borrar capa", "eng":"Delete layer", "fre":"Effacer couche"},
		MoveLayer: {"cat":"Moure la capa", "spa":"Mover la capa", "eng":"Move layer", "fre":"Déplacer la couche"},
		ToTheTop: {"cat":"A sobre de tot","spa":"Encima de todo", "eng":"To the top", "fre":"En haut de"},
		Up: {"cat":"A sobre","spa":"Encima", "eng":"Up", "fre":"Au-dessus"},
		Down: {"cat":"A sota", "spa":"Debajo::", "eng":"Down", "fre":"Au-dessous"},
		ToTheEnd: {"cat":"A sota de tot", "spa":"Debajo de todo", "eng":"To the end", "fre":"En bas"},
		ComputeQuality: {"cat":"Calcula la qualitat", "spa":"Calcula la calidad", "eng":"Compute the quality", "fre":"Calculer la qualité"},
		EditStyle: {"cat":"Edita estil", "spa":"Editar estilo", "eng":"Edit style", "fre":"Modifier le style"},
		ofEditingStyle: {"cat":"de editar l'estil", "spa":"de editar el estilo", "eng":"of editing the style", "fre":"pour modifier le style"},
		StyleName: {"cat":"Nom de l'estil", "spa":"Nombre del estilo", "eng":"Name of the style", "fre":"Nom du style"},
		ConfusionMatrix: {"cat":"Matriu de confusió", "spa":"Matriz de confusión", "eng":"Confusion matrix", "fre":"Matrice de confusion"},
		StatisticByCategory: {"cat": "Estadístic per categoria", "spa": "Estadístico por categoria", "eng": "Statistic by category", "fre": "Statistique par catégorie"},
		Statistic: {"cat": "Estadístic", "spa": "Estadístico", "eng": "Statistic", "fre": "Statistique"},
		Surface: {"cat":"Superfície", "spa":"Superficie", "eng":"Surface", "fre":"Surface"},
		RGBCombination: {"cat":"Combinació RGB", "spa":"Combinación RGB", "eng":"RGB combination", "fre":"Combinaison RVB"},
		Reclassification: {"cat":"Reclassificació", "spa":"Reclasificación", "eng":"Reclassification", "fre":"Reclassement"},
		RetrieveStyles: {"cat":"Recupera estils", "spa":"Recupera estilos", "eng":"Retrieve styles", "fre":"Récupérer les styles"},
		ShareStyle: {"cat":"Compartir estil", "spa":"Compartir estilo", "eng":"Share style", "fre":"Partager style"},
		DeleteStyle: {"cat":"Esborrar estil", "spa":"Borrar estilo", "eng":"Delete style", "fre":"Effacer style"},
		ComputeQuality: {"cat":"Calcula la qualitat", "spa":"Calcula la calidad", "eng":"Compute the quality", "fre":"Calculer la qualité"},
		toComputeTheQuality: {"cat":"de calcular la qualitat", "spa":"de calcular la calidad", "eng":"to compute the quality", "fre":"pour calculer la qualité"},
		NewLayerAdded: {"cat":"La nova capa afegida", "spa":"La nueva capa añadida", "eng":"The new added layer", "fre":"La nouvelle couche ajoutée"},
		notVisibleInCurrentZoom: {"cat":"no és visible al nivell de zoom actual del navegador", "spa":"no es visible al nivel de zoom actual del navegador", "eng":"is not visible in the current zoom level of the browser", "fre":"n'est pas visible au niveau du zoom actuel du navigateur"},
		toTheLayer: {"cat":"a la capa", "spa":"a la capa", "eng":"to the layer", "fre":"à la couche"},
		containsReferencesEraseContinue: {"cat":"conté referències a la capa que s'està intentant esborrar i deixarà de funcionar. Vols continuar", "spa": "contiene referencias a la capa que se está intentando borrar y dejará de funcionar. Desea continuar", "eng": "contains references to the layer that you are trying to erase and will stop working. Do you want to continue", "fre": "contient des références à la couche que vous essayez d'effacer et de cesser de travailler. Voulez-vous continuer"},
		containsReferencesStyleEraseContinue: {"cat":"conté referències a l'estil que s'està intentant esborrar i deixarà de funcionar. Vols continuar", "spa": "contiene referencias al estilo que se está intentando borrar y dejará de funcionar. Desea continuar", "eng": "contains references to the style that you are trying to erase and will stop working. Do you want to continue", "fre": "contient des références au style que vous essayez d'effacer et de cesser de travailler. Voulez-vous continuer"},
		ChooseTwoDifferentLayers: {"cat":"Cal triar dues capes diferents o la mateixa en estils i/o dates diferents.", "spa":"Es necesario elegir dos capas diferentes o la misma en estilos y/o fechas diferentes.", "eng":"You should choose two different layers or the same in different styles and/or dates.", "fre": "You should  choose two different layers or the same in different styles and/or dates."},
		_and_: {"cat": " i ", "spa": " y ", "eng": " and ", "fre": " et "},
		CombinationOf: {"cat": "Combinació de ", "spa": "Combinación de ", "eng": "Combination of ", "fre": "Combination of "},
		byCategoryOf: {"cat":"per categoria de","spa":"por categorías de","eng":"by category of", "fre":"par catégorie de"},
		byCategoriesOf: {"cat":"per les categories de", "spa":"para las categorías de", "eng":"by categories of", "fre":"par catégories des"},
		withStatisticsOf:{"cat":" amb estadistics de ","spa":" con estadísticos de ","eng":" with statistics of ", "fre":" avec statistiques par "},
		WrongNumberElementsInLine: {"cat": "Nombre d'elements incorrecte a la línia", "spa": "Número de elementos incorrecto en la línea", "eng": "Wrong number of elements in line","fre": "Wrong number of elements in line"},
		WrongValuesFormatInLine: {"cat": "Format incorrecte dels valors a la línia", "spa": "Formato incorrecto de los valores en la línea", "eng": "Wrong values format in line", "fre": "Wrong values format in line"},
		WrongOldValueInLine: {"cat": "Valor a canviar incorrecte a la línia", "spa": "Valor a cambiar incorrecto en la línea", "eng": "Wrong old value in line", "fre": "Ancienne valeur erronée dans la ligne"},
		CannotObtainValidResponseFromServer: {"cat":"No s'ha obtingut cap resposta vàlida del servidor sol·licitat", "spa":"No se ha obtenido ninguna respuesta válida del servidor solicitado", "eng":"Cannot obtain any valid response from server", "fre":"Aucune réponse valide n'a été obtenue du serveur demandé"},
		ServerURL: {"cat":"URL del servidor:", "spa":"URL del servidor:", "eng":"server URL:", "fre":"URL du serveur:"},
		SelectAllLayers: {"cat":"Seleccionar totes les capes", "spa":"Seleccionar todas las capas", "eng":"Select all layers", "fre":"Sélectionner toutes les couches"},
		ServerNotHaveLayerInBrowserReferenceSystem: {"cat":"Aquest servidor no té cap capa disponible en el sistema de referència actual del navegador", "spa":"Este servidor no tiene ninguna capa disponible en el sistema de referéncia actual del navegador", "eng":"This server don't have any layer in the browser actual reference system", "fre":"Ce serveur n'a aucune couche disponible dans le système de référence actuel du navigateur"},
		ValidURLMustBeProvided: {"cat":"Cal indicar una adreça vàlida", "spa":"Se debe indicar una dirección válida","eng":"A valid URL must be provided","fre":"Vous devez indiquer une adresse valide"},
		ChooseOneFromList: {"cat":"Seleccciona'n un de la llista", "spa":"Escoja uno de la lista","eng": "Choose one from list", "fre":"Sélectionnez un objet de la liste"},
		toShowInformationOrHelp: {"cat":"per mostrar informació o ajuda", "spa":"para mostrar información o ayuda","eng":"to show information or help", "fre":"pour afficher des informations ou de l'aide"},
		AddReclassifiedLayerAsNewStyle: {"cat":"Afegeix capa reclassificada com un nou estil", "spa":"Añada capa reclasificada como un nuevo estilo","eng":"Add reclassified layer as a new style", "fre":"Ajouter une couche reclassée en tant que nouveau style"},
		LayerToReclassify: {"cat":"Capa a reclassificar", "spa":"Capa a reclasificar", "eng":"Layer to reclassify", "fre":"Couche à reclassifier"},
		ReclassifyingExpression: {"cat":"Fórmula de reclassificació", "spa":"Fórmula de reclasificación:", "eng":"Reclassifying expression", "fre":"Formule de reclassement"},
		ResultOfReclassificationAddedAsNewStyleWithName: {"cat":"El resultat de la reclassificació serà afegit com a un estil nou de nom", "spa":"El resultado de la reclasssificación será añadido como un estilo nuevo de nombre", "eng":"The result of the reclassification will be added as a new style with name", "fre":"Le résultat du reclassement sera ajouté en tant que nouveau style avec le nom"},
    LayerForExpression: {"cat":"Capa per a la fórmula", "spa":"Capa para la fórmula", "eng":"Layer for the expression", "fre":"Couche pour l'expression"},
    WriteInExpression: {"cat":"Escriu a la fórmula", "spa":"Escribe en fórmula", "eng":"Write in expression", "fre":"Ecrire à la formule"},
    OperatorsFunctionsForExpression: {"cat":"Operadors i funcions per a la fórmula", "spa":"Operadores y funciones para la fórmula", "eng":"Operators and functions for the expression", "fre":"Opérateurs et fonctions pour l'expression"},
    ResultOfSelectionAddedAsNewLayerStyleWithName: {"cat":"El resultat de la selecció serà afegit com a una capa/estil nou de nom", "spa":"El resultado de la selección será añadido como una capa/estilo nuevo de nombre", "eng":"The result of the selection will be added as a new layer/style with name", "fre":"Le résultat de la sélection sera ajouté en tant que nouveau couche/style avec le nom"},
    AddGeometricOverlayLayerBetweenTwoCategoricalLayers: {"cat":"Afegir una capa de superposició geomètrica entre dues capes categòriques", "spa":"Añadir una capa de superposición geométrica entre dos capas categóricas", "eng":"Add a geometric overlay layer between two categorical layers", "fre":"Ajouter un couche de superposition géométrique entre deux couche catégoriels"},
    AddGeometricOverlay: {"cat":"Afegir superposició geomètrica", "spa":"Añadir superposición geométrica", "eng":"Add geometric overlay", "fre":"Ajouter une superposition géométrique"},
    AddStatisticalFieldsToCategoricalLayerFromAnotherLayer: {"cat":"Afegir camps estadístics a una capa categòrica des d'una altra capa (de qualsevol tipus)", "spa":"Añada capa combinada a partir de dues capas existentes", "eng":"Add statistical fields to a categorical layer from another layer (of any type)", "fre":"Ajouter des champs statistiques à une couche catégorielle à partir d'une autre couche (de tout type)"},
    AddStatisticalFields: {"cat":"Afegir camps estadíscs", "spa":"Añadir campos estadísticos", "eng":"Add statistical fields", "fre":"Ajouter des champs statistiques"},
	NewLayerFromServer:{"cat":"Capa nova de servidor", "spa":"Capa nueva de servidor", "eng":"New layer from server", "fre":"Nouvelle couche du serveur"},
	NewLayerFromDisk:{"cat":"Capa nova de disc local", "spa":"Capa nueva de disco local", "eng":"New layer from local drive", "fre":"Nouvelle couche du lecteur local"},
	NewLayerFromURL:{"cat":"Capa nova des de URL", "spa":"Capa nueva desde URL", "eng":"New layer from URL", "fre":"Nouvelle couche du URL"},
    SpecifyServerURL: {"cat":"Especifica l'adreça URL del servidor", "spa":"Especifique la dirección URL del servidor", "eng":"Specify the server URL", "fre":"Spécifiez l'adresse URL du serveur"},
    orChooseOnFromServiceList: {"cat":"o Seleccciona'n un de la llista de serveis", "spa":"o Escoja uno de la lista de servicios", "eng":"or Choose one from service list", "fre":"ou sélectionnez un des services de la liste"},
		ofAddingLayerToBrowser: {"cat":"d'afegir capes al navegador", "spa":"de añadir capas al navegador", "eng":"of adding a layer to browser", "fre":"pour ajouter des couches au navigateur"},
		toMakeCalculationsOfLayers: {"cat":"per fer càlculs de capes", "spa":"para hacer cálculos de capas", "eng":"to make calculations of layers", "fre":"pour réaliser de calculs des couches"},
		toCombineLayers: {"cat":"per combinar capes", "spa":"para combinar capas", "eng":"to combine layers", "fre":"pour correspondre des couches"},
		toReclassifyLayer: {"cat":"per reclassificar la capa", "spa":"para reclasificar la capa", "eng":"to reclassify the layer", "fre":"pour reclassifier de couche"},
    WriteValueInExpression: {"cat":"Escriu valor a la fórmula", "spa":"Escribe valor en fórmula", "eng":"Write value in expression", "fre":"Écrire une valeur dans l'expression"},
    RecommendedRangeOfValues: {"cat":"Interval de valors recomenats", "spa":"Intervalo de valores recomendados", "eng":"Recommended range of values", "fre":"Intervalle des valeurs recommandées"},
    anyValue: {"cat":"qualsevol valor", "spa":"cualquier valor", "eng":"any value", "fre":"toute valeur"},
    constant: {"cat":"constant", "spa":"constante", "eng":"constant", "fre":"constant"},
    SelectedInLayer: {"cat":"Seleccionada a la capa", "spa":"Seleccionada en la capa", "eng":"Selected in the layer", "fre":"Sélectionné dans la couche"},
    byDefault: {"cat":"per defecte","spa":"por defecto","eng":"by default", "fre":"par défaut"},
		OnlyShowValuesOfLayer: {"cat":"Mostra només els valors de la capa", "spa":"Muestra solo los valores de la capa", "eng":"Only show the values of the layer", "fre":"Afficher uniquement les valeurs de la couche"},
    ofTheStyle: {"cat":"de l'estil", "spa":"del estil", "eng":"of the style", "fre":"du style"},
    ofTheField: {"cat":"del camp", "spa":"del campo", "eng":"of the field", "fre":"du champ"},
		thatConformFollowingConditions: {"cat":"que complexien les condicions següents", "spa":"que cumplen las siguientes condiciones", "eng":"that conform the following conditions", "fre":"qui se conforment aux conditions suivantes"},
    NexusWithNextCondition: {"cat":"Nexe amb la següent condició", "spa":"Nexo con la siguiente condición", "eng":"Nexus with next condition", "fre":"Nexus avec la prochaine condition"},
    TheResultOfSelectionAddedAsNewStyleWithName: {"cat":"El resultat de la selecció serà afegit com a un estil nou de nom", "spa":"El resultado de la selección será añadido como un estilo nuevo de nombre", "eng":"The result of the selection will be added as a new style with name", "fre":"Le résultat de la sélection sera ajouté en tant que nouveau style avec le nom"},
		ofQueryByAttributeSelectionByCondition: {"cat":"de selecció per condició","spa":"de selección por condición", "eng":"of query by attribute selection by condition", "fre":" pour sélection par condition"},
		ofRGBCombination: {"cat":"de combinació RGB", "spa":"de combinación RGB", "eng":"of RGB combination", "fre":"pour combinaison RVB"},
    SelectThreeComponentsOfLayer: {"cat":"Sel·lecciona les 3 components de la capa", "spa":"Selecciona las 3 componentes de la capa", "eng":"Select the three components of the layer", "fre":"Sélectionnez les trois composants de la couche"},
    Component: {"cat":"Component", "spa":"Componente", "eng":"Component", "fre":"Composant"},
    RGBCombinationAddedAsNewStyleWithName: {"cat":"La combinació RGB serà afegida com a un estil nou de nom", "spa":"La combinación RGB será añadida como un estilo nuevo de nombre", "eng":"The RGB combination will be added as a new style with name", "fre":"La combinaison RVB sera ajouté en tant que nouveau style avec le nom"},
		SelectionStatisticValue: {"cat":"Selecció del valor estadístic", "spa":"Selección del valor estadístico","eng":"Selection of statistic value", "fre":"Sélection de la valeur statistique"},
		StatisticalValueToDisplayForLayer: {"cat":"Valor estadístic a mostrar per la capa", "spa":"Valor estadístico para mostrar para la capa", "eng":"Statistical value to display for the layer", "fre":"Valeur statistique à afficher pour la couche"},
    StatisticalValueOf: {"cat":"Valor estadístic de", "spa":"Valor estadístico de", "eng":"Statistical value of", "fre":"Valeur statistique des"},
    Ascending: {"cat":"Ascendent", "spa":"Ascendiente", "eng":"Ascending", "fre":"Ascendant"},
    Descending: {"cat":"Descendent", "spa":"Descendiente", "eng":"Descending", "fre":"Descendant"},
    CannotEditStyleNeverVisualized: {"cat":"No es pot editar un estil no visualitzat", "spa":"No es puede editar un estilo no visualizado", "eng":"You cannot edit a style never visualized", "fre":"Vous ne pouvez pas éditer un style jamais visualisé"},
    StyleLayer: {"cat":"Estil de la capa", "spa":"Estilo de la capa", "eng":"Style of the layer", "fre":"Style de la couche"},
    ValueForStretchingColor: {"cat":"Valors per l'estirament de color", "spa":"Valores para el estiramiento de color", "eng":"Value for stretching of color", "fre":"Valeur pour l'étirement de la couleur"},
    computed: {"cat":"calculat", "spa":"calculado", "eng":"computed", "fre":"calculé"},
    Adopt: {"cat":"Adoptar", "spa":"Adoptar", "eng":"Adopt", "fre":"Adopter"},
    SunPositionForComputationIllumination: {"cat":"Posició del sol pel càlcul de la il·luminació", "spa":"Posició del sol para el cálculo de la iluminación", "eng":"Sun position for the computation of the illumination", "fre":"Position du soleil par le calcul de l'éclairement"},
    Azimuth: {"cat":"Azimut", "spa":"Azimut", "eng":"Azimuth", "fre":"Azimut"},
    originNorthNorthClockwiseDegress: {"cat":"origen al nord nord i en sentit horari (en graus)", "spa":"origen en el norte norte y en el sentido de las agujas del reloj (en grados)", "eng":"origin north north and clockwise (in degress)", "fre":"origine au nord nord et dans le sens des aiguilles d'une montre (en degrés)"},
		Elevation: {"cat":"Elevació", "spa":"Elevación", "eng":"Elevation", "fre":"Élévation"},
    fromGroundDegress: {"cat":"des del terra (en graus)", "spa":"desde el suelo (en grados)", "eng":"from the ground (in degress)", "fre":"à partir du sol (en degrés)"},
    ReliefExaggerationFactor: {"cat":"Factor d'exageració del relleu", "spa":"Factor de exageración del relieve", "eng":"Relief exaggeration factor", "fre":"Facteur d'exagération du relief"},
    Greyscale: {"cat": "Escala de grisos", "spa": "Escala de grises", "eng": "Greyscale", "fre": "Niveaux de gris"},
    IncorrectAzimuth: {"cat":"Azimut incorrecte. Hauria de ser un número entre 0 i 360. Aplicant el valor per defecte", "spa":"Azimut incorrecto. Debería ser un número entre 0 y 360. Aplicando el valor por defecto", "eng":"Incorrect azimuth. It should be a number between 0 and 360. Applying the default value", "fre":"Azimut incorrect. Il doit s'agir d'un nombre compris entre 0 et 360. Application de la valeur par défaut"},
    IncorrectElevation:{"cat":"Elevació incorrecta. Hauria de ser un número entre 0 i 90. Aplicant el valor per defecte", "spa":"Elevación incorrecta. Debería ser un número entre 0 y 90. Aplicando el valor por defecto", "eng":"Incorrect elevation. It should be a number between 0 and 90. Applying the default value", "fre":"Élévation incorrect. Il doit s'agir d'un nombre compris entre 0 et 90. Application de la valeur par défaut"},
    IncorrectReliefExaggerationFactor: {"cat":"Factor d'exageració del relleu incorrecte. Hauria de ser un número major de 0.0001. Aplicant el valor per defecte", "spa":"Factor de exageración del relieve incorrecta. Debería ser un número mayor que 0.0001. Aplicando el valor por defecto", "eng":"Incorrect relief exaggeration factor. It should be a number bigger than 0.0001. Applying the default value", "fre":"Facteur d'exagération du relief incorrect. Il doit s'agir d'un nombre supérieur à 0,0001. Application de la valeur par défaut"},
		ofModifingName: {"cat":"de modificar el nom", "spa":"de modificar el nombre", "eng":"of modifing the name", "fre":"pour modifier le nom"},
    LayerNameInLegend: {"cat":"Nom de la capa a la llegenda", "spa":"Nombre de la capa en la leyenda", "eng":"Name of the layer in the legend", "fre":"Nom de la couche dans la légende"},
		forShowingLinageInformation: {"cat":"de mostrar la informació del llinatge", "spa":"de mostrar la información del linaje", "eng":"for showing the linage information", "fre":"pour afficher les informations de lignage"},
		forShowingQualityInformation: {"cat":"de mostrar la informació de qualitat", "spa":"de mostrar la información de calidad", "eng":"for showing the quality information", "fre":"pour afficher l'information de qualité"},
		ofUserFeedback: {"cat":"de valoracions dels usuaris", "spa":"de valoraciones de los usuarios", "eng":"of user feedback", "fre":"pour la rétroaction de l'utilisateur"},
	  _withStatisticOf_: {"cat":" amb estadistics de ","spa":" con estadísticos de ","eng":" with statistic of ", "fre":" avec statistiques des "},
		StatisticalDescriptorDisplayNeedSelected: {"cat":"Cal sel·leccionar el descriptor estadístic a mostrar per la capa", "spa":"Debe seleccionar el descriptor estadístico para mostrar para la capa", "eng":"The statistical descriptor to display for the layer needs to be selected", "fre":"Le descripteur statistique à afficher pour la couche doit être sélectionné"}
	},
  storymap:{
		SelectStory: {"cat":"Selecciona un relat", "spa":"Selecciona un relato", "eng":"Select a story", "fre":"Sélectionnez une histoire"},
		NoStoryInThisArea: {"cat":"No hi ha cap relat associat a aquesta zona", "spa":"No hay ningún relato asociado a esta zona", "eng":"There are no stories associated with this area", "fre":"Il n'y a pas d'histoires associées à cette zone"},
		WrongFormat_mm_center_Parameter: {"cat":"Format del paràmetre mm-center incorrecte", "spa":"Formato del parametro mm-center icnorrecto", "eng":"Wrong format in mm-center parameter", "fre":"Format incorrect dans le paramètre mm-center"},
		ParameterValueFoundIs: {"cat":"El valor del paràmetre indicat és:", "spa":"El valor del parámetro indicado es:", "eng":"The parameter value found is:", "fre":"La valeur de paramètre trouvée est:"},
		WrongFormat_mm_time_Parameter: {"cat":"Format del paràmetre mm-time incorrecte", "spa":"Formato del parámetro mm-time icnorrecto", "eng":"Wrong format in mm-time parameter", "fre":"Format incorrect dans le paramètre mm-time"},
		WrongFormat_mm_sels_Parameter: {"cat":"Format del paràmetre mm-sels incorrecte", "spa":"Formato del parametro mm-sels icnorrecto", "eng":"Wrong format in mm-sels parameter", "fre":"Format incorrect dans le paramètre mm-sels"},
	},
	tresD:{
		Graphic_3D: {"cat":"Gràfic 3D", "spa":"Gráfico 3D", "eng":"3D Graphic", "fre":"Diagramme 3D"},
		VerticalScale: {"cat":"Escala vertical", "spa":"Escala vertical", "eng":"Vertical scale", "fre":"Échelle verticale"},
  },
	canviprj:{
		LongLatConversionNotImplementedforRefSys: {"cat":"Pas a longitud/latitud no implementat per aquest sistema de referència", "spa":"Paso a longitud/latitud no implementado para este sistema de referencia", "eng":"Longitude/latitude conversion has not been implemented for this reference system", "fre":"Conversion à longitude/latitude pas implémenté pour ce système de référence"},
		MapCoordConversionNotImplementedInRefSys: {"cat":"Pas a coordenades mapa no implementat per aquest sistema de referència", "spa":"Paso a coordenades mapa no implementado para este sistema de referencia", "eng":"Map coordinates conversion has not been implemented for this reference system", "fre":"Conversion à coordonnées de la carte pas implémenté pour ce système de référence."},
		LambertConformalConicZoneIII_NTF: {"cat":"Lambert Cònica Conforme Zona III - NTF", "spa":"Lambert Cónica Conforme Zona III - NTF", "eng":"Lambert Conformal Conic Zone III - NTF", "fre":"Lambert Conique Conforme Zone III –NTF"},
		LambertConformalConicZoneIIext_NTF: {"cat":"Lambert Cònica Conforme Zona IIext - NTF", "spa":"Lambert Cónica Conforme Zona IIext - NTF", "eng":"Lambert Conformal Conic Zone IIext - NTF", "fre":"Lambert Conique Conforme Zone IIext–NTF"},
		LambertConformalConicZoneIIIext_NTF: {"cat":"Lambert Cònica Conforme Zona IIIext - NTF", "spa":"Lambert Cónica Conforme Zona IIIext - NTF", "eng":"Lambert Conformal Conic Zone IIIext - NTF", "fre":"Lambert Conique Conforme Zone IIIext –NTF"},
		LambertConformalConicICCMediterranianRegion: {"cat":"Lambert Cònica Conforme ICC Regió Mediterrània", "spa":"Lambert Cónica Conforme ICC Región Mediterránea", "eng":"Lambert Conformal Conic ICC Mediterranian Region", "fre":"Lambert Conique Conforme ICC Région Méditerranéenne"},
		MercatorParallel_41d25m_ED50: {"cat":"Mercator paral·lel 41° 25' - ED50", "spa":"Mercator paralelo 41°25' - ED50", "eng":"Mercator parallel 41°25' - ED50",  "fre":"Mercator parallèle 41°25' - ED50"},
		MercatorParallel_41d25m_WGS84: {"cat":"Mercator paral·lel 41° 25' - WGS84", "spa":"Mercator paralelo 41°25' - WGS84", "eng":"Mercator parallel 41°25' - WGS84", "fre":"Mercator parallèle 41°25' - WGS84"},
		MercatorParallel_40d36m_ED50: {"cat":"Mercator paral·lel 40° 36' - ED50", "spa":"Mercator paralelo 40°36' - ED50", "eng":"Mercator parallel 40°36' - ED50", "fre":"Mercator parallèle 40°36' – ED50"},
		MercatorParallelEquator_ED50: {"cat":"Mercator paral·lel Equador - ED50", "spa":"Mercator paralelo Ecuador - ED50", "eng":"Mercator parallel Equator - ED50", "fre":"Mercator parallèle Equateur – ED50"},
		MercatorParallelEquator_WGS84: {"cat":"Mercator paral·lel Equador - WGS84", "spa":"Mercator paralelo Ecuador - WGS84", "eng":"Mercator parallel Equator - WGS84", "fre":"Mercator parallèle Equateur- WGS84"},
		WebMercator: {"cat":"Web Mercator", "spa":"Web Mercator", "eng":"Web Mercator", "fre":"Web Mercator"},
	},
	capavola:{
    		Proj: {"cat":"Proj", "spa":"Proy", "eng":"Proj","fre":"Proj"},
		DeviceLocation: {"cat":"Ubicació dispositiu", "spa":"Ubicación dispositivo", "eng":"Device location","fre":"Emplacement de l'appareil"},
		AroundZone: {"cat":"Zona al voltant", "spa":"Zona alrededor", "eng":"Around zone","fre":"Zone autour"},
		GoTo: {"cat":"Anar-hi", "spa":"Ir", "eng":"Go to","fre":"Aller à"},
		ofGoToCoordinate: {"cat":"d'anar a coordenada", "spa":"de ir a coordenada", "eng":"of go-to coordinate", "fre":"pour aller à la coordonnée"},
		RequestedPointOutsideBrowserEnvelope: {"cat":"El punt sol·licitat està fora de l'àmbit de navegació", "spa":"El punto solicitado está fuera del ámbito de navegación", "eng":"The requested point is outside browser envelope", "fre":"Le point requis se trouve dehors le milieu de navigation"},
		toInsertNewPoints: {"cat":"per inserir punts nous", "spa":"para insertar puntos nuevos", "eng":"to insert new points", "fre":"pour insérer de nouveaux points"},
		UserDeniedRequestGeolocation: {"cat":"L'usuari ha denegat la sol·licitud de geolocalització", "spa":"El usuario ha denegado la solicitud de geolocalización", "eng":"User denied the request for geolocation","fre":"L'utilisateur a refusé la demande de géolocalisation"},
		LocationInfoUnavailable: {"cat":"La informació sobre la ubicació no està disponible", "spa":"La información sobre la ubicación no está disponible", "eng":"Location information is unavailable","fre":"Les informations de localisation ne sont pas disponibles"},
		RequestGetUserLocationTimedOut: {"cat":"S'ha esgotat el temps d'espera de la sol·licitud per obtenir la ubicació de l'usuari", "spa":"Se ha agotado el tiempo de espera de la solicitud para obtener la ubicación del usuario", "eng":"Request to get user location timed out","fre":"La demande d’obtention de l’emplacement de l’utilisateur a expiré"},
		UnknownErrorObtainingLocation: {"cat":"S'ha produït un error desconegut durant l'obtenció de la ubicació", "spa":"Se ha producido un error desconocido durante la obtención de la geolocalización", "eng":"An unknown error occurred while obtaining the location","fre":"Une erreur inconnue s'est survenue lors de l'obtention de l'emplacement"},
		CoordIncorrectFormat: {"cat":"Format de les coordenades erroni", "spa":"Formato de las coordenadas erróneo", "eng":"Coordinate format is incorrect", "fre":"Format des coordonnées erroné"},
		NumericalValueMustBeIndicated: {"cat":"S'ha d'indicar un valor numèric", "spa":"Se debe indicar un valor numérico", "eng":"A numerical value must be indicated", "fre":"Vous devez indiquer une valeur numérique"},
		GeolocationNotSupportedByBrowser: {"cat":"La geolocalització no està suportada en aquest navegador", "spa":"La geolocalización no está soportada en este navegador", "eng":"Geolocation is not supported by this browser", "fre":"La géolocalisation n'est pas prise en charge dans ce navigateur"},
  },
	commands:{
		ZoomSizeIncorrectFormat: {"cat":"Format del valor del costat de zoom erroni", "spa":"Formato del lado de zoom erróneo", "eng":"Zoom size format is incorrect.", "fre":"Format des zoom erroné"},
		NumericalValueIsRequired: {"cat":"S'ha d'indicar un valor numèric", "spa":"Se debe indicar un valor numérico", "eng":"A numerical value is required", "fre":"Vous devez indiquer une valeur numérique"},
		ZoomSizeRequestedNotAvailableBrowser: {"cat":"El costat de zoom sol·licitat no és un dels costats disponibles en aquest navegador.", "spa":"El lado de zoom solicitado no es uno de los lados disponibles en este navegador.", "eng":"The zoom size requested is not available in this browser.", "fre":"La taille de zoom demandée n'est pas disponible dans ce navigateur."},
		CoordIncorrectFormat: {"cat":"Format de les coordenades erroni", "spa":"Formato de las coordenadas erróneo", "eng":"Coordinate format is incorrect", "fre":"Format des coordonnées erroné"},
		TwoNumericalValuesRequiredFormat: {"cat":"S'ha d'indicar dos valors numèrics en el format", "spa":"Se debe indicar dos valores numéricos en el formato", "eng":"Two numerical values are required with the format", "fre":"Deux valeurs numériques sont requises dans le format"},
		SelectionsIncorrectFormat: {"cat":"Format de les consultes erroni", "spa":"Formato de las consultas erróneo", "eng":"Query format is incorrect", "fre":"Format des requete erroné"},
		LyQNameRequired: {"cat":"S'han d'indicar l'identificador de la capa, la consulta i el nom del nou estil en el format", "spa":"Se debe indicar el identificador de la capa, la consulta y el nombre del nuevo estilo en el formato", "eng":"The layer identifier, query, and new style name must be specified in the format", "fre":"L'identifiant de la couche, la requête et le nom du nouveau style doivent être spécifiés dans le format"},
	},
	consola:{
		ofWatchingReportsConsole: {"cat":"de veure els informes de la consola",  "spa":"de ver los informes de la consola", "eng":"of watching the reports in the console", "fre":"pour regarder les rapports dans la console"},
		DeleteAll: {"cat":"Esborra-ho tot", "spa":"Borrar todo", "eng":"Delete all","fre":"Tout effacer"},
  },
	consult:{
		NoDataForRequestedPoint: {"cat":"No hi ha dades pel punt consultat", "spa":"No hay datos para el punto consultado", "eng":"There are no data for the requested point", "fre":"Pas de données au point consulté"},
		andActiveQueryableLayers: {"cat":"i les capes consultables actives", "spa":"y las capas consultables activas", "eng":"and active queryable layers", "fre":"et les couches consultables activées"},
		ChartValueCopiedClipboardFormat: {"cat": "Els valors del gràfic han estat copiats al portaretalls en format", "spa": "Los valores del gráfico han sido copiados al portapapeles en formato", "eng": "The values of the chart have been copied to clipboard in the format", "fre": "Les valeurs du graphique ont été copiées dans le presse-papiers dans le format"},
		MessagesNotDisplayedAgain: {"cat": "Aquests missatge no es tornarà a mostrar", "spa": "Este mensaje no se volverá a mostrar", "eng": "These messages will not be displayed again", "fre": "Ces messages ne seront plus affichés"},
		CopySeriesValues: {"cat":"Copia valors de la sèrie", "spa":"Copiar valores de la serie", "eng":"Copy series values","fre":"Copier les valeurs des séries"},
		FollowingCoordinateSelected: {"cat":"S'ha seleccionat la següent coordenada","spa":"Se ha seleccionado la siguiente coordenada", "eng":"The following coordinate has been selected", "fre":"La coordonnée suivante a été sélectionnée"},
		IfCorrectValidateIt: {"cat":"Si és correcte, ja la podeu validar.", "spa":"Si es correcta, ya la puede validar.", "eng":"If it is correct, you can already validate it.", "fre":"Si correcte, vous pouvez la valider."},
		BrowserClosedReturnForm: {"cat":"Es tancarà la finestra de navegació i tornarà al formulari.", "spa":"Se cerrará la ventana de navegación y volverá al formulario.", "eng":"Browser window will be closed and will return to form.", "fre":"La fenêtre du navigateur va se fermer et vous serez redirigés vers le formulaire."},
		IfIncorrectClicksViewAgain: {"cat":"Si és incorrecte, torni a clicar sobre la vista.", "spa":"Si es incorrecta, vuelva a cliquear sobre la vista.", "eng":"If it is incorrect, click on the view again.", "fre":"Si incorrecte, cliquez une autre fois sur la vue."},
		ValidateCoordinate: {"cat":"Validar Coordenada","spa": "Validar Coordenada", "eng":"Validate Coordinate","fre":"Valider coordonnée"},
		WaitingForData: {"cat":"Esperant dades", "spa":"Esperando datos", "eng":"Waiting for data", "fre":"En attente des données"},
		ProfileTransversalCutQueriedLine: {"cat": "Perfil del tall transversal de la línia consultada", "spa": "Perfil del corte transversal de la línea consultada", "eng": "Profile of the transversal cut of the queried line", "fra": "Profil de la coupe transversale de la ligne interrogée"},
		PreviousLayer: {"cat":"Anterior capa", "spa":"Anterior capa", "eng":"Previous layer", "fre":"Précédente couche"},
		NextLayer: {"cat":"Següent capa", "spa":"Siguiente capa", "eng":"Next layer", "fre":"Suivant couche"},
		noconsul_htm: {"cat":"noconsul.htm", "spa":"noconsul_spa.htm", "eng":"noconsul_eng.htm", "fre":"noconsul_fre.htm"},
		NotImplementedYetRESTful: {"cat":"De moment no implementat per RESTful", "spa":"De momento no implementado para RESTful", "eng":"Not implemented yet for RESTful", "fre":"Pas encore implémenté pour RESTful"},
  },
	ctipica:{
		AnyMatch: {"cat":"Cap coincidència", "spa":"Ninguna coincidencia", "eng":"Any match", "fre":"Aucune coïncidence"},
		UpdatingList: {"cat":"Actualitzant la llista", "spa":"Actualizando la lista", "eng":"Updating the list","fre":"La liste est en train d'être actualisée"},
		toBeShownInFrame: {"cat":"per a mostrar al frame", "spa":"para mostrar en el frame", "eng":"to be shown in the frame", "fre":"à montrer au frame"},
		notInTypicalQueryLayerList: {"cat":"no és a la llista de capes amb consulta típica", "spa":"no está en la lista de capas con consulta típica", "eng":"is not in the typical query layer list", "fre":"ne se trouve pas dans la liste de couches avec recherche typique"},
		UseBrowserToolsPlaceOnView: {"cat":"Usa les eines del navegador per situar-te sobre la vista.\nA continuació fés clic sobre la vista per determinar la coordenada i la informació del punt a validar.\nPer finalitzar, prem [Validar Coordenada] o [Cancel·lar] des de la finestra de validació.", "spa":"Utiliza las herramientas del navegador para situarte sobre la vista.\nA continuación haz clic sobre la vista para determinar la coordenada y la información del punto a validar.\nPara finalizar aprieta [Validar Coordenada] o [Cancelar] desde la ventana de validación.", "eng":"You have to use browser tools to place on the view.\n Later, you have to click on the view to determine the coordinate\nand the information of the point of validating.\nTo finish you have to click [Validate coordinate] or [Cancel] from the validation window.", "fre":"Utilisez les outils du navigateur pour vous placer sur la vue.\n Ensuite cliquez sur la vue pour déterminer la coordonné\net l'information du point à valider.\nFinalement, pressez [Valider Coordonnée] où [Annuler] de la fenêtre de validation."},
		isIncorrect: { "cat": "és incorrecte", "spa": "es incorrecta", "eng": "is incorrect", "fre": "est incorrecte"},
  },
	download:{
		ErrorWhileSendingTryAgain: {"cat":"S'ha produït algun error durant l'enviament del fitxer. Torna-ho a intentar", "spa":"Se ha producido algun error durante el envío del fichero. Vuélvalo a intentar", "eng":"An error has been occurred while sending the file. Try again", "fre":"Une erreur vient de se produire pendant l'envoi du fichier. Réessayez"},
		LayerDownloadedTakeMinutes: {"cat":"La generació de la descàrrega de la capa podria trigar alguns minuts", "spa":"La generación de la descarga de la capa podría demorarse algunos minutos", "eng":"Generation of layer to be downloaded can take some minutes", "fre":"La création du téléchargement de la couche pourrai prendre quelques minutes"},
		PreparingRequestedLayer: {"cat":"Preparant la capa sol·licitada", "spa":"Preparando la capa solicitada", "eng":"Preparing the requested layer", "fre":"En préparant la couche demandée"},
		SelectiveDownloadZone: {"cat": "Descàrrega selectiva de la zona", "spa": "Descarga selectiva de la zona", "eng": "Selective download of the zone", "fre": "Téléchargement sélectif de la zone"},
		MMZ_MMZX_NotInstalledDownload: {"cat":"Pel format MMZ o MMZX (ISO 19165-1), si no teniu instal·lat o actualitzat el Lector Universal de Mapes del MiraMon, <a href=\"http://www.creaf.uab.cat/miramon/mmr/cat\" target=\"_blank\">descarregueu-lo</a>", "spa":"Para el formato MMZ o MMZX (ISO 19165-1), si no tiene instalado o actualizado el Lector Universal de Mapas de MiraMon, <a href=\"http://www.creaf.uab.cat/miramon/mmr/esp\" target=\"_blank\">descárguelo</a>", "eng":"For the MMZ or MMZX format (ISO 19165-1), if you don't have installed or updated MiraMon Universal Map Reader, please, <a href=\"http://www.creaf.uab.cat/miramon/mmr/usa\" target=\"_blank\">download it</a>", "fre":"Pour le format MMZ ou MMZX (ISO 19165-1), si vous n'avez pas installé où actualisé le Lecteur Universel de Cartes du MiraMon, please, <a href=\"http://www.creaf.uab.cat/miramon/mmr/usa\" target=\"_blank\">download it</a>"},
		ViewLayers_MMZ_MMZX_InstalledMM: {"cat":"Per poder visualitzar les capes en format MMZ o MMZX (ISO 19165-1) cal tenir correctament instal·lat el programa MiraMon.", "spa":"Para poder visualitzar las capas en formato MMZ o MMZX (ISO 19165-1) es necessario tener correctamente instalado el programa MiraMon.", "eng":"In order to be able to view the layers in MMZ or MMZX format (ISO 19165-1), an installed version of the MiraMon software is required.", "fre":"Pour pouvoir visualiser les couches en MMZ du format MMZX (ISO 19165-1), et la version installée du logiciel MiraMon est nécessaire"},
		DownloadLayerCompleted: {"cat": "Descàrrega la capa completa", "spa": "Descarga de la capa completa", "eng": "Download the complete layer", "fre": "Téléchargement de la couche complète"},
		ofDownloading: {"cat":"de descarregar", "spa":"de descargar", "eng":"of downloading", "fre":"de téléchargement"},
  },
	params:{
		ViewAreaBackgroundColor: {"cat":"Color de fons de la vista", "spa":"Color de fondo de la vista", "eng":"Background color of the view area", "fre":"Couleur du fond"},
		SituationRectangleColor: {"cat":"Color del rectangle de situació", "spa":"Color del rectángulo de situación", "eng":"Color of the situation rectangle", "fre":"Couleur du rectangle de situation"},
		WidthOfTheView: {"cat":"Mida de l\'ample de la vista", "spa":"Tamaño del ancho de la vista", "eng":"Width of the view", "fre":"Dimensions de la largeur de la vue"},
		LateralJumpPerc: {"cat":"Perc. de salt lateral", "spa":"Porc. de salto lateral", "eng":"Lateral jump perc.", "fre":"Pourc. de saut latéral"},
		ShowCleanMap_View: {"cat":"Mostra <u>v</u>ista del mapa neta", "spa":"Muestra <u>v</u>ista del mapa limpia", "eng":"Show a clean map <u>v</u>iew", "fre":"Afficher une <u>v</u>ue de carte propre"},
		ZoomPan_2Clicks: {"cat":"Zoom i pan basat en <u>2</u> simples clics (ergonòmic)", "spa":"Zoom y pan basado en <u>2</u> simples clics (ergonómico)", "eng": "Zoom and pan based in <u>2</u> simples clicks (ergonomic)", "fre":"Zoom et pan basé en <u>2</u> simples clics (ergonomique)"},
		ZoomPan_1ClickDrag: {"cat":"Zoom i pan en <u>1</u> clic i arrossegant", "spa":"Zoom y pan en <u>1</u> clic y arrastrando", "eng":"Zoom and pan with <u>1</u> click and dragging", "fre":"Zoom et pan en <u>1</u> cliques et glisser"},
		NOfFigures: {"cat":"N. decimals", "spa":"N. decimales", "eng":"N. of figures", "fre":"N. décimales"},
		Corners: {"cat":"Cantonades", "spa":"Esquinas", "eng":"Corners", "fre":"Coins"},
		None_underlined: {"cat":"c<u>a</u>p", "spa":"ningun<u>a</u>", "eng":"<u>n</u>one", "fre":"<u>a</u>ucune"},
		None_underlined_char: {"cat":"a", "spa":"a", "eng":"n", "fre":"a"},
		Proj_underlined_p: {"cat":"<u>P</u>roj", "spa":"<u>P</u>roy", "eng":"<u>P</u>roj", "fre":"<u>P</u>roj"},
		Proj_underlined_r: {"cat":"P<u>r</u>oj", "spa":"P<u>r</u>oy", "eng":"P<u>r</u>oj", "fre":"P<u>r</u>oj"},
		ShowWindow_underlined: {"cat":"<u>M</u>ostra finestra", "spa":"<u>M</u>uestra ventana", "eng":"S<u>h</u>ow window", "fre":"A<u>f</u>ficher la fenêtre"},
		ShowWindow_underlined_char: {"cat":"m", "spa":"m", "eng":"h", "fre":"f"},
		JsonConfigurationFile: {"cat":"Fitxer de configuració JSON", "spa":"Fichero de configuración JSON", "eng":"JSON configuration file", "fre":"Fichier de configuration JSON)"},
		changesAboveWillBeApplied: {"cat":"s'’aplicaran els canvis anteriors", "spa":"los cambios anteriores se aplicarán", "eng":"changes above will be applied", "fre":"les modifications ci-dessus s'appliqueront"},
		ofChangingParameters: {"cat":"de canviar paràmetres", "spa":"de cambiar parámetros", "eng":"of changing parameters", "fre":"pour changement de paramètres"}
  },
	editavec:{
		InsertTransactionObjectIntoLayer: {"cat": "La transacció d'inserció a la capa", "spa": "La transacción de inserción a la capa", "eng":"The insert transaction of the object into the layer", "fre": "L'opération d'insertion de l'objet dans la couche"},
		hasFailed: {"cat":"ha fallat", "spa": "ha fallado", "eng":"has failed", "fre": "a échoué"},
		InsertTransactionObject: {"cat": "La transacció d'inserció de l'objecte", "spa": "La transacción de inserción del objeto", "eng": "The insert transaction of the object", "fre": "La transaction d'insertion de l'objet"},
		successfullyCompleted: {"cat":"ha finalitzat amb èxit", "spa": "ha finalizado con éxito", "eng":"has been successfully completed", "fre": "a été achevé avec succès"},
		toReportResultTransaction: {"cat":"per informar del resultat de la transacció", "spa":"para informar del resultado de la transacción", "eng":"to report the result of the transaction", "fre":"pour rapporter le résultat de la transaction"},
		ClickOnViewDeterminesCoordNewPoint:{"cat": "Un clic sobre la vista determina la coordenada del nou punt. Ompliu en aquesta fitxa les propietats del objecte que conegueu i premeu [D'acord] per enviar el punt al servidor.", "spa": "Un clic sobre la vista determina la coordenada del punto nuevo. Rellena en esta ficha los datos del objeto que conozcas y pulsa [Aceptar] para enviar el punto al servidor.", "eng": "A click on the view determines the coordinate of the new point. In this tab fill the properties of the feature that you known and press [OK] to send the point to the server.", "fre": "Un clic sur la vue détermine la coordonnée du nouveau point. Dans cet onglet remplissez les propriétés de la fonctionnalité que vous connaissez et appuyez sur [Accepter] pour envoyer le point au serveur."},
  },
	histopie:{
		ImageValuesCopiedClipboardFormat: {"cat": "Els valors de la imatge han estat copiats al portaretalls en format", "spa": "Los valores de la image han sido copiados al portapapeles en formato", "eng": "The values of the image have been copied to clipboard in the format", "fre": "Les valeurs du graphique ont été copiées dans le presse-papier dans le format"},
		ClassDescription: {"cat": "Descripció de classe", "spa": "Descripción de clase", "eng": "Class description", "fre": "Description de la classe"},
		ClassValue: {"cat": "Valor de classe", "spa": "Valor de classe", "eng": "Class value", "fre": "Valeur de classe"},
		AreaPercentage: {"cat": "Percentatge de l'àrea", "spa": "Porcentaje del área", "eng": "Percentage of area", "fre": "Pourcentage de zone"},
		ClassCentalValue: {"cat": "Valor central de la classe", "spa": "Valor central de la classe", "eng": "Class cental value", "fre": "Classe valeur centrale"},
		CountByCategory: {"cat": "Recompte per categoria", "spa": "Cuenta por categoría", "eng": "Count by category", "fre": "Compter par catégorie"},
		AreaByCategory: {"cat": "Àrea per categoria", "spa": "Área por categoría", "eng": "Area by category", "fre": "Zone par catégorie"},
		Similarity: {"cat": "Semblança", "spa": "Similitud", "eng": "Similarity", "fra": "Similitude"},
		MeanPlusDev: {"cat": "Mitjana+desv", "spa": "Media+desv", "eng": "Mean+dev", "fre": "Moyenne+écart"},
		MeanMinusDev: {"cat": "Mitjana-desv", "spa": "Media-desv", "eng": "Mean-dev", "fre": "Moyenne-écart"},
		ChartValuesCopiedClipboard: {"cat": "Els valors del gràfic han estat copiats al portaretalls", "spa": "Los valores del gráfico han sido copiados al portapapeles", "eng": "The values of the chart have been copied to clipboard", "fre": "Les valeurs du graphique ont été copiées dans le presse-papier"},
  },
	datahora:{
	    ofData: {"cat":"de","spa":"de", "eng":"","fre":""},
	    PrepMonthOfTheYear0: {"cat": "de gener", "spa": "de enero", "eng": "January", "fre": "Janvier"},
		PrepMonthOfTheYear1: {"cat": "de febrer", "spa": "de febrero", "eng": "February", "fre": "Février"},
		PrepMonthOfTheYear2: {"cat": "de març", "spa": "de marzo", "eng": "March", "fre": "Mars"},
		PrepMonthOfTheYear3: {"cat": "d\'abril", "spa": "de abril", "eng": "April", "fre": "Avril"},
		PrepMonthOfTheYear4: {"cat": "de maig", "spa": "de mayo", "eng": "May", "fre": "Mai"},
		PrepMonthOfTheYear5: {"cat": "de juny", "spa": "de junio", "eng": "June", "fre": "Juin"},
		PrepMonthOfTheYear6: {"cat": "de juliol", "spa": "de julio", "eng": "July", "fre": "Juillet"},
		PrepMonthOfTheYear7: {"cat": "d\'agost", "spa": "de agosto", "eng": "August", "fre": "Août"},
		PrepMonthOfTheYear8: {"cat": "de setembre", "spa": "de setiembre", "eng": "September", "fre": "Septembre"},
		PrepMonthOfTheYear9: {"cat": "d\'octubre", "spa": "de octubre", "eng": "October", "fre": "Octobre"},
		PrepMonthOfTheYear10: {"cat": "de novembre", "spa": "de noviembre", "eng": "November", "fre": "Novembre"},
		PrepMonthOfTheYear11: {"cat": "de desembre", "spa": "de diciembre", "eng": "December", "fre": "Décembre"},
		MonthOfTheYear0: {"cat": "Gener", "spa": "Enero", "eng": "January", "fre": "Janvier"},
		MonthOfTheYear1: {"cat": "Febrer", "spa": "Febrero", "eng": "February", "fre": "Février"},
		MonthOfTheYear2: {"cat": "Març", "spa": "Marzo", "eng": "March", "fre": "Mars"},
		MonthOfTheYear3: {"cat": "Abril", "spa": "Abril", "eng": "April","fre": "Avril"},
		MonthOfTheYear4: {"cat": "Maig", "spa": "Mayo", "eng": "May","fre": "Mai"},
		MonthOfTheYear5: {"cat": "Juny", "spa": "Junio", "eng": "June","fre": "Juin"},
		MonthOfTheYear6: {"cat": "Juliol", "spa": "Julio", "eng": "July","fre": "Juillet"},
		MonthOfTheYear7: {"cat": "Agost", "spa": "Agosto", "eng": "August","fre": "Août"},
		MonthOfTheYear8: {"cat": "Setembre", "spa": "Setiembre", "eng": "September","fre": "Septembre"},
		MonthOfTheYear9: {"cat": "Octubre", "spa": "Octubre", "eng": "October","fre": "Octobre"},
		MonthOfTheYear10: {"cat": "Novembre", "spa": "Noviembre", "eng": "November","fre": "Novembre"},
		MonthOfTheYear11: {"cat": "Desembre", "spa": "Diciembre", "eng": "December","fre": "Décembre"}
  },
	cntxmenu2:{
		statistics:
		{
			display:
			{
				SampleMessage: {"cat":"Cal sel·leccionar el descriptor estadístic a mostrar per la capa", "spa":"Debe seleccionar el descriptor estadístico para mostrar para la capa", "eng":"The statistical descriptor to display for the layer needs to be selected", "fre":"Le descripteur statistique à afficher pour la couche doit être sélectionné"}
			}
		}
	}
}
